### ISSUE TITLE
No BridgeData file

### ISSUE THREAD

**Issue by qyaaang** [kiran-darji/bridge-builder#1]
Hi there.

There are no BridgeData.py in the folder.

**Comment by kiran-darji** [comment]
Hi, I have now added the file. Unfortunately I do not have the original file, so what I have done is copy and paste the code directly from the documentation.docx file. It should hopefully still run smoothly.

But please be advised, I created this 5 years ago and I have not touched it since. I couldn't tell you what versions are required for python and the required libraries.
